apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-server-service
  annotations:
    # Configure for secure service-to-service authentication
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
spec:
  template:
    metadata:
      annotations:
        # Scaling configuration
        run.googleapis.com/min-scale: "1"
        run.googleapis.com/max-scale: "20"
        
        # Resource allocation
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "2Gi"
        
        # Startup and health probes
        run.googleapis.com/startup-probe-timeout: "120s"
        run.googleapis.com/startup-probe-period: "10s"
        run.googleapis.com/startup-probe-failure-threshold: "10"
        
        # VPC and networking (if needed)
        # run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
        
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: mcp-server-service-account@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - name: mcp-server
        image: gcr.io/PROJECT_ID/mcp-server-service:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        # Cloud Run automatic authentication configuration
        - name: EXPECTED_AUDIENCE
          value: "https://mcp-server-service-PROJECT_ID.a.run.app"
        - name: GCP_PROJECT
          value: "PROJECT_ID"
        # Allowed service accounts for additional validation (optional)
        - name: ALLOWED_SERVICE_ACCOUNTS
          value: "agent-service-account@PROJECT_ID.iam.gserviceaccount.com,mcp-client@PROJECT_ID.iam.gserviceaccount.com"
        # Security configuration
        - name: SECURITY_LEVEL
          value: "cloud_run_managed"
        - name: AUTHENTICATION_MODE
          value: "cloud_run_automatic"
        # Optional business rules
        - name: BUSINESS_HOURS_ONLY
          value: "false"
        # Other service configurations
        - name: OPA_URL
          value: "http://localhost:8181"
        - name: KMS_KEY_PATH
          value: "projects/PROJECT_ID/locations/global/keyRings/mcp-ring/cryptoKeys/mcp-key"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        # Startup probe
        startupProbe:
          httpGet:
            path: /mcp-server/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /mcp-server/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /mcp-server/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
